# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"make_namer": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://tetrascience.github.io/parsify/"

git_url = "https://github.com/tetrascience/parsify/tree/master/"

def custom_doc_links(name): return None
