# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['make_namer']

# Cell
from collections import defaultdict

def make_namer(prefix='g'):
    """Creates a dictionary that generates short names (suitable for regex groups) given arbitrary inputs."""
    count = 0
    def next_name():
        nonlocal prefix
        nonlocal count
        count += 1
        return f'{prefix}{count}'
    return defaultdict(next_name)